# This workflow is usesd to test a JavaScript Action Basic using input/output

name: Run JavaScript Action Basic
run-name: Run of "JavaScript Action Basic" by @${{ github.actor }} triggered on @${{ github.event_name }}

on:
  workflow_dispatch:

jobs:
  RunJavaScriptAction:
    name: Runs a JavaScript Action Basic to test input and output variables
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run the JavaScript Action Basic that will print the varible who-to-greet
        id: myJavaScriptAction
        uses: marcusmai-telia/actions-javascript-action-basic@main
        with:
          who-to-greet: 'Telia'
          my-Secret: ${{ secrets.MY_TEST_SECRET }}


      - name: Print out the variable time from JavaScript Action Basic
        run: echo "The output is = ${{ steps.myJavaScriptAction.outputs.time }}"
        shell: bash