# This workflow is usesd to test a TypeScript Action using input/output

name: Run TypeScript Action Basic
run-name: Run of "Typescript Action" by @${{ github.actor }} triggered on @${{ github.event_name }}

on:
  workflow_dispatch:

jobs:
  RunTypeScriptAction:
    name: Runs a TypeScript Action to test input and output variables
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run the TypeScript Action that will print the variable who-to-greet
        id: myTypeScriptAction
        uses: marcusmai/actions-typescript-action@main
        #with:
          #who-to-greet: 'Telia'
          #my-Secret: ${{ secrets.MY_TEST_SECRET }}


      #- name: Print out the variable time from TypeScript Action Basic
      #  run: echo "The output is = ${{ steps.myTypeScriptAction.outputs.time }}"
      #  shell: bash